import type { Sku } from "./types";

/** Catálogo extra (≥50 SKU en total con los 8 de planta). No cambia la ocupación de huecos. */
const EXTRA: Array<Pick<Sku, "sku" | "name" | "category" | "abc" | "unitsPerPallet" | "weightKg" | "minStock" | "maxStock">> = [
  { sku: "ALI-TOM-400", name: "Tomate frito 400 g", category: "alimentacion_seca", abc: "B", unitsPerPallet: 96, weightKg: 420, minStock: 80, maxStock: 400 },
  { sku: "ALI-PASTA-500", name: "Pasta espirales 500 g", category: "alimentacion_seca", abc: "A", unitsPerPallet: 80, weightKg: 400, minStock: 100, maxStock: 600 },
  { sku: "ALI-LEN-1K", name: "Lenteja pardina 1 kg", category: "alimentacion_seca", abc: "B", unitsPerPallet: 60, weightKg: 600, minStock: 60, maxStock: 300 },
  { sku: "ALI-GARB-1K", name: "Garbanzo pedrosillano 1 kg", category: "alimentacion_seca", abc: "B", unitsPerPallet: 60, weightKg: 600, minStock: 60, maxStock: 300 },
  { sku: "ALI-AZU-1K", name: "Azúcar blanco 1 kg", category: "alimentacion_seca", abc: "A", unitsPerPallet: 80, weightKg: 800, minStock: 120, maxStock: 700 },
  { sku: "ALI-SAL-1K", name: "Sal marina 1 kg", category: "alimentacion_seca", abc: "C", unitsPerPallet: 100, weightKg: 1000, minStock: 40, maxStock: 200 },
  { sku: "ALI-HAR-1K", name: "Harina de trigo 1 kg", category: "alimentacion_seca", abc: "A", unitsPerPallet: 70, weightKg: 700, minStock: 90, maxStock: 450 },
  { sku: "ALI-CAF-250", name: "Café molido 250 g", category: "alimentacion_seca", abc: "A", unitsPerPallet: 120, weightKg: 300, minStock: 70, maxStock: 350 },
  { sku: "ALI-TE-100", name: "Té infusión 100 ud.", category: "alimentacion_seca", abc: "C", unitsPerPallet: 200, weightKg: 80, minStock: 30, maxStock: 150 },
  { sku: "ALI-GAL-400", name: "Galleta María 400 g", category: "alimentacion_seca", abc: "B", unitsPerPallet: 90, weightKg: 360, minStock: 50, maxStock: 250 },
  { sku: "ALI-ACEIT-314", name: "Aceituna hojiblanca 314 ml", category: "alimentacion_seca", abc: "B", unitsPerPallet: 72, weightKg: 280, minStock: 40, maxStock: 200 },
  { sku: "ALI-ATUN-3P", name: "Atún en aceite pack 3", category: "alimentacion_seca", abc: "A", unitsPerPallet: 110, weightKg: 330, minStock: 80, maxStock: 400 },
  { sku: "BEB-NAR-1L", name: "Zumo naranja 1 L", category: "bebidas", abc: "A", unitsPerPallet: 72, weightKg: 720, minStock: 90, maxStock: 450 },
  { sku: "BEB-COL-2L", name: "Cola 2 L", category: "bebidas", abc: "A", unitsPerPallet: 48, weightKg: 960, minStock: 100, maxStock: 500 },
  { sku: "BEB-CER-33", name: "Cerveza 33 cl pack 24", category: "bebidas", abc: "A", unitsPerPallet: 40, weightKg: 800, minStock: 80, maxStock: 400 },
  { sku: "BEB-VIN-75", name: "Vino tinto 75 cl", category: "bebidas", abc: "B", unitsPerPallet: 56, weightKg: 500, minStock: 40, maxStock: 200 },
  { sku: "BEB-AGU-50", name: "Agua 50 cl pack 24", category: "bebidas", abc: "B", unitsPerPallet: 48, weightKg: 600, minStock: 70, maxStock: 350 },
  { sku: "BEB-LECH-AV", name: "Bebida avena 1 L", category: "bebidas", abc: "B", unitsPerPallet: 72, weightKg: 720, minStock: 40, maxStock: 180 },
  { sku: "FRE-QUES-1K", name: "Queso semicurado 1 kg", category: "frescos", abc: "A", unitsPerPallet: 50, weightKg: 500, minStock: 40, maxStock: 160 },
  { sku: "FRE-MANTE-250", name: "Mantequilla 250 g", category: "frescos", abc: "B", unitsPerPallet: 80, weightKg: 200, minStock: 30, maxStock: 140 },
  { sku: "FRE-HUEVO-12", name: "Huevos M docena", category: "frescos", abc: "A", unitsPerPallet: 60, weightKg: 180, minStock: 50, maxStock: 200 },
  { sku: "FRE-JAMON-Y", name: "Jamón york 150 g", category: "perecederos", abc: "A", unitsPerPallet: 100, weightKg: 150, minStock: 40, maxStock: 180 },
  { sku: "FRE-SALCH-200", name: "Salchicha fresca 200 g", category: "perecederos", abc: "B", unitsPerPallet: 90, weightKg: 180, minStock: 30, maxStock: 120 },
  { sku: "FRE-POLLO-BAN", name: "Pechuga pollo bandeja", category: "perecederos", abc: "A", unitsPerPallet: 40, weightKg: 320, minStock: 25, maxStock: 100 },
  { sku: "FRE-ENSAL-MIX", name: "Ensalada mix 200 g", category: "perecederos", abc: "B", unitsPerPallet: 80, weightKg: 160, minStock: 20, maxStock: 80 },
  { sku: "CON-GUIS-1K", name: "Guisantes congelados 1 kg", category: "congelados", abc: "B", unitsPerPallet: 48, weightKg: 480, minStock: 40, maxStock: 200 },
  { sku: "CON-PESC-400", name: "Filete merluza 400 g", category: "congelados", abc: "A", unitsPerPallet: 50, weightKg: 200, minStock: 30, maxStock: 120 },
  { sku: "CON-PIZZ-1U", name: "Pizza margarita", category: "congelados", abc: "A", unitsPerPallet: 60, weightKg: 240, minStock: 40, maxStock: 180 },
  { sku: "CON-VERD-MIX", name: "Menestra congelada 1 kg", category: "congelados", abc: "C", unitsPerPallet: 48, weightKg: 480, minStock: 20, maxStock: 100 },
  { sku: "CON-NUG-400", name: "Nuggets pollo 400 g", category: "congelados", abc: "B", unitsPerPallet: 70, weightKg: 280, minStock: 30, maxStock: 140 },
  { sku: "NF-PAP-HIG", name: "Papel higiénico 12 r", category: "no_food", abc: "A", unitsPerPallet: 40, weightKg: 200, minStock: 50, maxStock: 250 },
  { sku: "NF-DETER-5L", name: "Detergente 5 L", category: "no_food", abc: "B", unitsPerPallet: 36, weightKg: 180, minStock: 30, maxStock: 120 },
  { sku: "NF-LAVAV-1L", name: "Lavavajillas 1 L", category: "no_food", abc: "B", unitsPerPallet: 80, weightKg: 80, minStock: 40, maxStock: 160 },
  { sku: "NF-BOLSA-30", name: "Bolsa basura 30 L", category: "no_food", abc: "C", unitsPerPallet: 100, weightKg: 40, minStock: 20, maxStock: 80 },
  { sku: "NF-ESPON-6", name: "Estropajo pack 6", category: "no_food", abc: "C", unitsPerPallet: 200, weightKg: 30, minStock: 15, maxStock: 60 },
  { sku: "NF-PILAS-AA", name: "Pilas AA pack 8", category: "no_food", abc: "C", unitsPerPallet: 150, weightKg: 45, minStock: 20, maxStock: 80 },
  { sku: "NF-FOIL-30", name: "Papel aluminio 30 m", category: "no_food", abc: "C", unitsPerPallet: 120, weightKg: 60, minStock: 20, maxStock: 80 },
  { sku: "NF-FILM-50", name: "Film transparente 50 m", category: "no_food", abc: "C", unitsPerPallet: 120, weightKg: 40, minStock: 15, maxStock: 60 },
  { sku: "ALI-MIEL-500", name: "Miel azahar 500 g", category: "alimentacion_seca", abc: "B", unitsPerPallet: 80, weightKg: 400, minStock: 25, maxStock: 100 },
  { sku: "ALI-ACEIT-VIR", name: "AOVE virgen extra 1 L", category: "alimentacion_seca", abc: "A", unitsPerPallet: 60, weightKg: 600, minStock: 50, maxStock: 250 },
  { sku: "ALI-VINAG-1L", name: "Vinagre de Jerez 1 L", category: "alimentacion_seca", abc: "C", unitsPerPallet: 72, weightKg: 720, minStock: 20, maxStock: 80 },
  { sku: "FRE-CREMA-200", name: "Crema nata 200 ml", category: "frescos", abc: "B", unitsPerPallet: 96, weightKg: 192, minStock: 30, maxStock: 120 },
];

export const EXTRA_SKUS: Sku[] = EXTRA.map((row, i) => ({
  id: `sku-x-${String(i + 1).padStart(2, "0")}`,
  uom: "caja",
  ...row,
}));
